from gym_sailingroute.envs.sailingroute_env import SailingrouteEnv
from gym_sailingroute.envs.sailingroute_env import SailingrouteEnv_simplest
#from gym_sailingroute.envs.sailingroute_extrahard_env import SailingrouteExtraHardEnv
